### ISSUE TITLE
Bug: Light Intro video is not showing up (empty src)

### ISSUE THREAD

**Issue by mokaymokay** [sanctuarycomputer/sanctu-dot-com#176]
https://app.contentful.com/spaces/zb716c7gdesq/entries/6iSGKgmnwYDrOUpcB3wIIM

But it does work on the Light case study page

**Comment by nahbee10** [comment]
@mokaymokay 
Got this video show up on [this preview](https://sanctu-dot-m5dkxubbi-sanctucompu.vercel.app/)
The reason is because the video was linked to 'asset' instead of 'video'!!

- before the fix : the video was linked to asset
<img width="1056" alt="Screen Shot 2023-01-31 at 6 31 59 PM" src="https://user-images.githubusercontent.com/12539032/215908648-3bd76a52-40ff-4ce4-80db-0728589db854.png">

- [line from components/Work.js](https://github.com/sanctuarycomputer/sanctu-dot-com/blob/c693bdeb23cd66920fd37730ee946a602faaf542/components/Work.js#L63) to get the src of video 
<img width="442" alt="Screen Shot 2023-01-31 at 6 40 32 PM" src="https://user-images.githubusercontent.com/12539032/215908938-f15003c8-d142-4eec-ab72-3b2a99d0bf53.png">

**Comment by nahbee10** [comment]
follow-up on the former comment:
I added file-type validation to [Work > asset field](https://app.contentful.com/spaces/zb716c7gdesq/content_types/work/fields) to only accept attachment and images(not video)
<img width="1135" alt="Screen Shot 2023-01-31 at 6 50 14 PM" src="https://user-images.githubusercontent.com/12539032/215910088-a5d33858-8ce6-40f6-ae9a-1774fc2516f4.png">

**Comment by mokaymokay** [comment]
Nice, TY for adding the validation!
